INFO     root:test_api_all.py:83 导入大于2000条数据，导入失败是否自动化： YES
INFO     root:test_api_all.py:171 ********正在执行 导入大于2000条数据，导入失败**********
INFO     root:test_api_all.py:216 请求方法POST，请求头{'Authorization': 'bearer e983dcb9-7966-4193-8622-a35615e5a3db'},请求接口https://bss-api.haoshitong.com/api/customer/import
INFO     root:test_api_all.py:217 请求参数:
{},
请求文件{"file":"F:/Test/Interface/Python自动化/git_api/test/data\\员工导入大于2000.xlsx"}
DEBUG    urllib3.connectionpool:connectionpool.py:959 Starting new HTTPS connection (1): bss-api.haoshitong.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:437 https://bss-api.haoshitong.com:443 "POST /api/customer/import HTTP/1.1" 200 None
INFO     root:test_api_all.py:220 返回:
 {"result":["导入文件数据超出最大长度","导入文件数据超出最大长度"],"resCode":0,"resMessage":"success"}